### ISSUE TITLE
Screenshot doesn't match an installed version

### ISSUE THREAD

**Issue by donadigo** [bbuhler/HostsManager#7]
We've rejected this app from releasing it on AppCenter. Please resolve this issue and release a new version.

The screenshot in the repo (https://github.com/bbuhler/HostsManager/blob/master/data/screenshots/main.png) doesn't match the app after the installation. Namely, the screenshot presents a header bar and additional functionality (like adding new entries) which doesn't exist in the installed version.

If you have a local WIP version somewhere that has this new functionality, you should probably set up 2 branches so that master remains clean.

**Comment by bbuhler** [comment]
The screenshot is fixed.
The new version has a header bar now but without the "add new entry" button.
